### ISSUE TITLE
Compatability with MIT's new Touchstone web interface?

### ISSUE THREAD

**Issue by terman** [meson800/touchstone-auth#9]
Have you tried touchstone-auth since MIT Touchstone changed its UI and process?

When I try (with verbose=True), I see:

  Logged in successfully to ...URL... without redirecting through Touchstone

But reading the page using the session produces the HTML for a Touchstone login:

  <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd”>
  <html>
  <head>
     ...
    <!-- Title —>
    <title>Touchstone@MIT : Please Authenticate</title>
  …

So I’m guessing that the module is still expecting the old-style MIT Touchstone authentication process?  Just double-checking that there's not some embarrasing pilot error at my end.

**Comment by meson800** [comment]
See issue #8. The Okta change means that I need to reverse engineer the
initial flow again. Even though it visually looks similar, it is very
different.

**Comment by meson800** [comment]
@terman I just pushed version 0.8.0; can you try it out (`pip install -U touchstone_auth`) and close this issue if it fixes your problem? Thanks for the initial report by the way; it's nice to hear that this is being used out in the wild :)

I expect v0.8.0 should work for any Shibboleth-protected applications. Newer MIT websites might use OIDC (or whatever they are moving to); currently `touchstone_auth` does not support that, but probably can once I have an example to work with.

**Comment by terman** [comment]
Working well, thanks!
